codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 75%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "src/**/*.test.ts"
  - "src/**/__tests__/**"
  - "src/types/**"
  - "src/index.ts"
  - "src/vite-env.d.ts"
  - "examples/**"
  - "scripts/**"
  - "docs/**"
  - "dist/**"
  - "coverage/**"
  - "*.config.*"